[build]
  command = "nuxt generate"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.vue"
  status = 200

[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"